// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ERGAyeHLit0w9bWr8SZ79GiJrssMMF8',
    appId: '1:513229661535:android:89bff18fc473176f3142ea',
    messagingSenderId: '513229661535',
    projectId: 'zerohunger-b8114',
    databaseURL: 'https://zerohunger-b8114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zerohunger-b8114.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASO3LG-jFVapyeDeuZyg1IrDjzHjO-eik',
    appId: '1:513229661535:web:9418ced5ed4ca63a3142ea',
    messagingSenderId: '513229661535',
    projectId: 'zerohunger-b8114',
    authDomain: 'zerohunger-b8114.firebaseapp.com',
    databaseURL: 'https://zerohunger-b8114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zerohunger-b8114.firebasestorage.app',
    measurementId: 'G-PF80W1CNN0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB6zCh-o8nNBmbo-KOfqB4ozCxhJjXm0c',
    appId: '1:513229661535:ios:e8064f6d70cd5dc43142ea',
    messagingSenderId: '513229661535',
    projectId: 'zerohunger-b8114',
    databaseURL: 'https://zerohunger-b8114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zerohunger-b8114.firebasestorage.app',
    iosBundleId: 'com.example.zerohunger',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB6zCh-o8nNBmbo-KOfqB4ozCxhJjXm0c',
    appId: '1:513229661535:ios:e8064f6d70cd5dc43142ea',
    messagingSenderId: '513229661535',
    projectId: 'zerohunger-b8114',
    databaseURL: 'https://zerohunger-b8114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zerohunger-b8114.firebasestorage.app',
    iosBundleId: 'com.example.zerohunger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASO3LG-jFVapyeDeuZyg1IrDjzHjO-eik',
    appId: '1:513229661535:web:a7ee89e018c1b9dd3142ea',
    messagingSenderId: '513229661535',
    projectId: 'zerohunger-b8114',
    authDomain: 'zerohunger-b8114.firebaseapp.com',
    databaseURL: 'https://zerohunger-b8114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zerohunger-b8114.firebasestorage.app',
    measurementId: 'G-Z31W8QCXJQ',
  );

}